# Form implementation generated from reading ui file 'game_layout.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(720, 820)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.numbersFrame = QtWidgets.QFrame(parent=self.centralwidget)
        self.numbersFrame.setGeometry(QtCore.QRect(10, 10, 371, 251))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.numbersFrame.setFont(font)
        self.numbersFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.numbersFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.numbersFrame.setObjectName("numbersFrame")
        self.layoutWidget = QtWidgets.QWidget(parent=self.numbersFrame)
        self.layoutWidget.setGeometry(QtCore.QRect(13, 20, 351, 221))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.button7 = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.button7.setCheckable(False)
        self.button7.setObjectName("button7")
        self.gridLayout.addWidget(self.button7, 0, 0, 1, 1)
        self.button8 = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.button8.setCheckable(False)
        self.button8.setObjectName("button8")
        self.gridLayout.addWidget(self.button8, 0, 1, 1, 1)
        self.button9 = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.button9.setCheckable(False)
        self.button9.setObjectName("button9")
        self.gridLayout.addWidget(self.button9, 0, 2, 1, 1)
        self.button4 = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.button4.setCheckable(False)
        self.button4.setObjectName("button4")
        self.gridLayout.addWidget(self.button4, 1, 0, 1, 1)
        self.button5 = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.button5.setCheckable(False)
        self.button5.setObjectName("button5")
        self.gridLayout.addWidget(self.button5, 1, 1, 1, 1)
        self.button6 = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.button6.setCheckable(False)
        self.button6.setObjectName("button6")
        self.gridLayout.addWidget(self.button6, 1, 2, 1, 1)
        self.button1 = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.button1.setCheckable(False)
        self.button1.setObjectName("button1")
        self.gridLayout.addWidget(self.button1, 2, 0, 1, 1)
        self.button2 = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.button2.setCheckable(False)
        self.button2.setObjectName("button2")
        self.gridLayout.addWidget(self.button2, 2, 1, 1, 1)
        self.button3 = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.button3.setCheckable(False)
        self.button3.setObjectName("button3")
        self.gridLayout.addWidget(self.button3, 2, 2, 1, 1)
        self.button0 = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.button0.setCheckable(False)
        self.button0.setChecked(False)
        self.button0.setObjectName("button0")
        self.gridLayout.addWidget(self.button0, 3, 0, 1, 1)
        self.buttonClear = QtWidgets.QPushButton(parent=self.centralwidget)
        self.buttonClear.setGeometry(QtCore.QRect(10, 360, 371, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonClear.setFont(font)
        self.buttonClear.setObjectName("buttonClear")
        self.buttonSubmit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.buttonSubmit.setGeometry(QtCore.QRect(10, 410, 371, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.buttonSubmit.setFont(font)
        self.buttonSubmit.setObjectName("buttonSubmit")
        self.userguessField = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.userguessField.setGeometry(QtCore.QRect(10, 270, 371, 81))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.userguessField.setFont(font)
        self.userguessField.setText("")
        self.userguessField.setMaxLength(4)
        self.userguessField.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.userguessField.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.userguessField.setReadOnly(True)
        self.userguessField.setObjectName("userguessField")
        self.resultsTextArea = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.resultsTextArea.setGeometry(QtCore.QRect(390, 10, 321, 481))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.resultsTextArea.setFont(font)
        self.resultsTextArea.setReadOnly(True)
        self.resultsTextArea.setObjectName("resultsTextArea")
        self.gamerulesTextArea = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.gamerulesTextArea.setGeometry(QtCore.QRect(10, 500, 701, 291))
        self.gamerulesTextArea.setObjectName("gamerulesTextArea")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 720, 19))
        self.menubar.setObjectName("menubar")
        self.menuGame = QtWidgets.QMenu(parent=self.menubar)
        self.menuGame.setObjectName("menuGame")
        self.menuHelp = QtWidgets.QMenu(parent=self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.gameNew = QtGui.QAction(parent=MainWindow)
        self.gameNew.setObjectName("gameNew")
        self.gameQuit = QtGui.QAction(parent=MainWindow)
        self.gameQuit.setObjectName("gameQuit")
        self.helpAbout = QtGui.QAction(parent=MainWindow)
        self.helpAbout.setObjectName("helpAbout")
        self.menuGame.addAction(self.gameNew)
        self.menuGame.addAction(self.gameQuit)
        self.menuHelp.addAction(self.helpAbout)
        self.menubar.addAction(self.menuGame.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.buttonClear.clicked.connect(self.userguessField.clear) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Bulls and Cows Game"))
        self.button7.setText(_translate("MainWindow", "7"))
        self.button7.setShortcut(_translate("MainWindow", "7"))
        self.button8.setText(_translate("MainWindow", "8"))
        self.button8.setShortcut(_translate("MainWindow", "8"))
        self.button9.setText(_translate("MainWindow", "9"))
        self.button9.setShortcut(_translate("MainWindow", "9"))
        self.button4.setText(_translate("MainWindow", "4"))
        self.button4.setShortcut(_translate("MainWindow", "4"))
        self.button5.setText(_translate("MainWindow", "5"))
        self.button5.setShortcut(_translate("MainWindow", "5"))
        self.button6.setText(_translate("MainWindow", "6"))
        self.button6.setShortcut(_translate("MainWindow", "6"))
        self.button1.setText(_translate("MainWindow", "1"))
        self.button1.setShortcut(_translate("MainWindow", "1"))
        self.button2.setText(_translate("MainWindow", "2"))
        self.button2.setShortcut(_translate("MainWindow", "2"))
        self.button3.setText(_translate("MainWindow", "3"))
        self.button3.setShortcut(_translate("MainWindow", "3"))
        self.button0.setText(_translate("MainWindow", "0"))
        self.button0.setShortcut(_translate("MainWindow", "0"))
        self.buttonClear.setText(_translate("MainWindow", "Clear"))
        self.buttonClear.setShortcut(_translate("MainWindow", "Backspace"))
        self.buttonSubmit.setText(_translate("MainWindow", "SUBMIT GUESS"))
        self.buttonSubmit.setShortcut(_translate("MainWindow", "Return"))
        self.resultsTextArea.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Your result will appear here.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Numbers: Enter a digit</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Backspace: Clear</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">ENTER: Submit</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">ESC: New game</span></p></body></html>"))
        self.gamerulesTextArea.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-weight:700;\">RULES</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">Find the secret 4-digit number!</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">The number cannot contain same digits!</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">BULL: Found correct digit on the correct position.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">COW: Found correct digit on a different position.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:700;\">EXAMPLE</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">Secret number = 1234</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">User guess = 0243</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">BULLS = 1, COWS = 2</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">because 2 is on the same position, </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">but 3 and 4 are on different positions.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">For reference:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"https://en.wikipedia.org/wiki/Bulls_and_cows\"><span style=\" font-size:11pt; text-decoration: underline; color:#0000ff;\">https://en.wikipedia.org/wiki/Bulls_and_cows</span></a></p></body></html>"))
        self.menuGame.setTitle(_translate("MainWindow", "&Game"))
        self.menuHelp.setTitle(_translate("MainWindow", "&Help"))
        self.gameNew.setText(_translate("MainWindow", "&New"))
        self.gameNew.setShortcut(_translate("MainWindow", "Esc"))
        self.gameQuit.setText(_translate("MainWindow", "&Quit"))
        self.gameQuit.setShortcut(_translate("MainWindow", "F10"))
        self.helpAbout.setText(_translate("MainWindow", "&About"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
