# Form implementation generated from reading ui file 'help_about_layout.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DialogHelpAboutBC(object):
    def setupUi(self, DialogHelpAboutBC):
        DialogHelpAboutBC.setObjectName("DialogHelpAboutBC")
        DialogHelpAboutBC.setWindowModality(QtCore.Qt.WindowModality.NonModal)
        DialogHelpAboutBC.resize(400, 227)
        DialogHelpAboutBC.setModal(False)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=DialogHelpAboutBC)
        self.buttonBox.setGeometry(QtCore.QRect(50, 190, 341, 41))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.helpaboutInfo = QtWidgets.QTextBrowser(parent=DialogHelpAboutBC)
        self.helpaboutInfo.setGeometry(QtCore.QRect(10, 10, 381, 181))
        self.helpaboutInfo.setObjectName("helpaboutInfo")

        self.retranslateUi(DialogHelpAboutBC)
        self.buttonBox.accepted.connect(DialogHelpAboutBC.accept) # type: ignore
        self.buttonBox.rejected.connect(DialogHelpAboutBC.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DialogHelpAboutBC)

    def retranslateUi(self, DialogHelpAboutBC):
        _translate = QtCore.QCoreApplication.translate
        DialogHelpAboutBC.setWindowTitle(_translate("DialogHelpAboutBC", "Dialog"))
        self.helpaboutInfo.setHtml(_translate("DialogHelpAboutBC", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-weight:700;\">BULLS AND COWS GAME</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"https://github.com/StrayFeral/bulls_and_cows_game\"><span style=\" font-size:10pt; text-decoration: underline; color:#0000ff;\">https://github.com/StrayFeral/bulls_and_cows_game</span></a></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">2024 by Evgueni Antonov</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Evgueni.Antonov@gmail.com</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">This game is free (GPL3 License).</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">I wrote it as an exercise in PyQt.</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogHelpAboutBC = QtWidgets.QDialog()
    ui = Ui_DialogHelpAboutBC()
    ui.setupUi(DialogHelpAboutBC)
    DialogHelpAboutBC.show()
    sys.exit(app.exec())
