.\" Manpage for bulls_and_cows_game_qt
.\" Contact Evgueni.Antonov@gmail.com to correct errors or typos.
.TH man 6 "11 February 2024" "1.0" "bulls_and_cows_game_qt man page"
.SH NAME
bulls_and_cows_game_qt - Classic game of Bulls and Cows, QT6 version.
.SH SYNOPSIS
bulls_and_cows_game_qt
.SH DESCRIPTION
This is a QT6 version of the classic game of Bulls and Cows. Run the game to see the instructions of how to play.

You may also want to check bulls_and_cows_game for a command-line version.
.SH OPTIONS
The bulls_and_cows_game_qt does not take any options.
.SH SEE ALSO
bulls_and_cows_game(6)
.SH BUGS
No known bugs.
.SH AUTHOR
Evgueni Antonov (Evgueni.Antonov@gmail.com)

