.\" Manpage for bulls_and_cows_game
.\" Contact Evgueni.Antonov@gmail.com to correct errors or typos.
.TH man 6 "11 February 2024" "1.0" "bulls_and_cows_game man page"
.SH NAME
bulls_and_cows_game - Classic game of Bulls and Cows, command-line version.
.SH SYNOPSIS
bulls_and_cows_game
.SH DESCRIPTION
This is a command-line version of the classic game of Bulls and Cows. Run the game to see the instructions of how to play.

You may also want to check bulls_and_cows_game_qt for a GUI QT version.
.SH OPTIONS
The bulls_and_cows_game does not take any options.
.SH SEE ALSO
bulls_and_cows_game_qt(6)
.SH BUGS
No known bugs.
.SH AUTHOR
Evgueni Antonov (Evgueni.Antonov@gmail.com)
